# Generated by Django 6.1.1 on 2026-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.TextField(help_text="A short, honest description. Avoid overstating results or status — see RULES.md's Truth Rule.")),
                ('tags', models.CharField(blank=True, help_text="Comma-separated, e.g. 'YOLOv8, Computer Vision'", max_length=300)),
                ('status', models.CharField(blank=True, choices=[('in_development', 'In development'), ('prototype', 'Prototype'), ('research', 'Research'), ('completed', 'Completed')], help_text="Leave blank if genuinely unsure — don't guess.", max_length=20)),
                ('external_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
