# Generated by Django 6.1.1 on 2026-09-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_notification_sent', models.BooleanField(default=False, help_text="Whether the Resend notification email succeeded. False doesn't mean the message was lost — it's still saved here regardless.")),
                ('is_reviewed', models.BooleanField(default=False, help_text="Mark once you've read/responded to this.")),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
