# Generated by Django 6.1.1 on 2026-09-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(default='Prakash Bishi', help_text='Comma-separated if more than one author.', max_length=300)),
                ('venue', models.CharField(blank=True, help_text='Journal, conference, or institution (for a thesis).', max_length=300)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_type', models.CharField(choices=[('paper', 'Paper'), ('thesis', 'Thesis'), ('preprint', 'Preprint')], max_length=20)),
                ('summary', models.TextField(blank=True, help_text="Optional abstract or short description. Leave blank if you'd rather just link out — don't overstate results.")),
                ('external_url', models.URLField(blank=True, help_text='Link to the paper/thesis/PDF if available.')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-year', '-created_at'],
            },
        ),
    ]
